package codigo;

public enum Tokens{
    RESERVADA,
    INT_CONSTANTE,
    STRING_CONSTANTE,
    SOMA,
    IGUAL,
    ABRE_CHAVES,
    FECHA_CHAVES,
    DIFERENTE,
    VIRGULA,
    PONTO_E_VIRGULA,
    IDENTIFICADOR,
    ATRIBUICAO,
    ABRE_PARENTESES,
    FECHA_PARENTESES,
    ERROR,
    MENOR_QUE,
    MAIOR_QUE,
    MENOR_IGUAL_QUE,
    MAIOR_IGUAL_QUE,
    SUBTRACAO,
    MULTIPLICACAO,
    DIVISAO,
    SOBRA_DIVISAO
}
