package codigo;

public enum Tokens {
    RESERVADA,
    INT_CONSTANTE,
    STRING_CONSTANTE,
    SOMA,
    IGUAL,
    DIFERENTE,
    PONTO_E_VIRGULA,
    IDENTIFICADOR,
    ATRIBUICAO,
    ABRE_PARENTESES,
    FECHA_PARENTESES,
    ERROR
}
